### ISSUE TITLE
EXASOL VM for Travis-CI needed

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-infrastructure#1]
We need a separate EXASOL VM instance accessible from Travic-CI for building forked repositories such as `vsimko/r-exasol`.

Previously, I used EXASOL public cloud instance but it only works one month. We need to setup this VM somewhere on our BigGIS infrastructure.

The main problem is that building process for `EXASOL/r-exasol` repository uses a hidden username/password to an EXASOL VM.

**Comment by vsimko** [comment]
Here is an example of failing build due to the missing Exasol VM
https://travis-ci.org/vsimko/r-exasol

**Comment by wipatrick** [comment]
Ok, I see. What design option would you think is a better fit: 
(a) vpn connection to our BigGIS infrastructure network or 
(b) arbitrary highport for EXASOL DB

Btw, the report also states that if your using 32bit apps you should install libstdc++ package:

```
warning: package libstdc++ 32bit is missing
  Mandatory for 32bit applications; install with:
  apt-get install libstdc++6:i386
```

**Comment by vsimko** [comment]
As pointed out by @marcelboldt in issue EXASOL/r-exasol#15, the connection to EXASOL database is not encrypted. But I still think that the simplest option is to open a highport for EXASOL DB.

**Comment by wipatrick** [comment]
@ooke 
- Is it possible to deploy the Exasol Docker container on Mesos? 
- Can you write a Dockerfile for building the Exasol Docker image for CI

**Comment by ooke** [comment]
@wipatrick 
- I do not know, what is needed for Mesos, but I think it should be possible.
- Dockerfile is also possible, but the executables packages are not available on the internet, I could use the free available EXASolo ISO image, would it be an option for you?

**Comment by wipatrick** [comment]
I mean we can test it.

Right now, I am working on setting up a virtual cluster on our BigGIS server in order to simulate a distributed infrastructure. 

This will include: 
- Vagrant for spinning up the VMs
- Ansible for automatically configuring a Mesos Cluster (vMaster, vSlaves)
- tbd

**Comment by vsimko** [comment]
is the VM available ?

**Comment by wipatrick** [comment]
As of now, no. There's no viable solution for connecting to the server from the outside world according to the internal security policies. Neither is dedicating a high port nor establishing a VPN connection from publicly hosted Travis CI VMs an option. Since Travis CI VMs are not having a static IP and in addition a changing subnet, there's also no option to set iptable rules accordingly for limiting access.

see:
http://stackoverflow.com/questions/18493149/travis-ci-static-ip-for-the-vm

I'd suggest you either set up some kind of proxy server at your location with a static IP or you setup a VM for CI locally to which Travis CI VMs can connect.

**Comment by wipatrick** [comment]
There is a official Exasol docker repository available. So this issue can be closed.

see:

https://github.com/EXASOL/docker-db

**Comment by vsimko** [comment]
When I fork the repository  https://github.com/EXASOL/docker-db, I'm not able to run automated tests on Travis-CI because the tests require a connection to a running database instance. Some dummy  sandbox would be nice.

However, I'm not editing my fork anymore, so it is actually not needed.
