### ISSUE TITLE
mysql - Vulnerability Detection Result

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-infrastructure#19]
On port 3306 from remote
It was possible to login as root with password "admin".
 
The remote MySQL service has the password `htr_pwd` for the user `htr`.

**Vulnerability Detection Result**
It was possible to login as user `htr` with password "htr_pwd".

**Comment by vsimko** [comment]
maybe just use `127.0.0.1:3306:3306` instead of `3306:3306`

**Comment by wipatrick** [comment]
are you referring to the MariaDB docker image used in M3?

**Comment by vsimko** [comment]
Probably. Our admins run some automated tests to see open ports on all machines.
This could have been some running instance from the past.
We're not using mysql/mariadb in biggis anymore.

**Comment by wipatrick** [comment]
This issue can be closed, since MariaDB was only used for some dirty testing for what it was sufficient. It is not maintained anymore in our project.
