### ISSUE TITLE
combine flink with gdal library

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-infrastructure#8]
For raster processing using flink, we also need GDAL library + java bindings (gdal.jar + JNI files).

On Debian/Ubuntu this can be installed as follows:

```
apt-get install libgdal-java
```

On Alpine Linux, it must be compiled from source.
There is an existing [gdal apk](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/gdal.) for Alpine, but it does not contain the java stuff.

**Comment by vsimko** [comment]
I compiled the whole gdal from source together with JNI libs. In the docs they say:

> To deploy you need gdal.jar in your class path, the 4 .so files (libgdalconstjni.so, libgdaljni.so, libogrjni.so and libosrjni.so) and libgdal.so in your shared library path.

Here are the commands I executed:

``` sh
# on my linux box
docker run --rm -ti yikaus/alpine-bash /bin/bash
```

``` sh
# now inside the alpine docker instance
apk add util-linux pciutils usbutils coreutils binutils findutils grep
apk add build-base gcc abuild binutils binutils-doc gcc-doc
apk add automake
apk add openjdk8
apk add apache-ant

wget http://download.osgeo.org/gdal/2.1.1/gdal-2.1.1.tar.gz
tar xfz gdal-2.1.1.tar.gz

cd gdal-2.1.1/
./configure --with-java
make
make install

cd swig/java/
make
make install
```

**Comment by wipatrick** [comment]
In addition, i needed to add the following package

``` sh
apk add swig
```

and create a symlink, since `configure` does not look for  _/usr/lib/jvm/java-1.8-openjdk_

``` sh
ln -s /usr/lib/jvm/java-1.8-openjdk /usr/lib/jvm/java-openjdk
```

**Comment by wipatrick** [comment]
The resulting image is huge.

``` sh
➜  gdal git:(master) ✗ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
biggis/base             gdal-2.1.1-v2       2d0de22598cf        About an hour ago   1.214 GB
```

Even if I remove the `gdal-2.1.1` folder it's still big.

``` sh
➜  gdal git:(master) ✗ docker images
REPOSITORY              TAG                  IMAGE ID            CREATED             SIZE
biggis/base             gdal-2.1.1-deleted   c7c0a5f07646        52 seconds ago      488.3 MB
```

The Dockerfile I used is the following:

``` Dockerfile
FROM alpine:3-4

MAINTAINER wipatrick

RUN apk add --no-cache gcc openjdk8
RUN apk add --no-cache --virtual build-deps \
            util-linux \
            coreutils \
            findutils \
            build-base \
            abuild \
            automake \
            apache-ant \
            swig && \
    curl -s http://download.osgeo.org/gdal/2.1.0/gdal-2.1.0.tar.gz | tar -xzf - -C / && \
    ln -s /usr/lib/jvm/java-1.8-openjdk /usr/lib/jvm/java-openjdk && \
    cd gdal-2.1.1/ && \
    ./configure --with-java && \
    make && \
    make install && \
    cd swig/java/ && \
    make && \
    make install && \
    apk del build-deps && \
    rm -rf /gdal-2.1.1
```

Therefore, I packaged the following compiled files into `gdal-libs.tar.gz` (24MB):
- libgdalconstjni.so
- libgdaljni.so
- libogrjni.so
- libosrjni.so
- libgdal.so.20.1.1 

_libgdal.so_ is a symlink to _libgdal.so.20.1.1_

``` sh
/usr/local/lib # ls -la
total 252812
drwxr-xr-x    4 root     root          4096 Jul 18 09:24 .
drwxr-xr-x   11 root     root          4096 Jul 18 09:22 ..
drwxr-xr-x    2 root     root          4096 Jul 18 08:07 gdalplugins
-rw-r--r--    1 root     root     180184762 Jul 18 08:07 libgdal.a
-rwxr-xr-x    1 root     root           939 Jul 18 08:07 libgdal.la
lrwxrwxrwx    1 root     root            17 Jul 18 08:07 libgdal.so -> libgdal.so.20.1.1
lrwxrwxrwx    1 root     root            17 Jul 18 08:07 libgdal.so.20 -> libgdal.so.20.1.1
-rwxr-xr-x    1 root     root      75375912 Jul 18 08:07 libgdal.so.20.1.1
-rwxr-xr-x    1 root     root         68584 Jul 18 08:07 libgdalconstjni.so
-rwxr-xr-x    1 root     root       1767816 Jul 18 08:07 libgdaljni.so
-rwxr-xr-x    1 root     root        956168 Jul 18 08:07 libogrjni.so
-rwxr-xr-x    1 root     root        491464 Jul 18 08:07 libosrjni.so
drwxr-xr-x    2 root     root          4096 Jul 18 08:07 pkgconfig
```

Now my question @vsimko:

I guess we don't need to put it inside `gdal-libs.tar.gz`. Do you know if **gdal.jar** will be provided by editing the `pom.xml`? 

``` xml
<dependency>
    <groupId>org.gdal</groupId>
    <artifactId>gdal</artifactId>
    <version>2.1.0</version>
</dependency>
```

Other than the libs inside `gdal-libs.tar.gz` what additional packages will you need to be installed in the alpine base image besides _openjdk-8_? 
- [gcc?](https://pkgs.alpinelinux.org/package/edge/main/armhf/gcc)
- [gdal?](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/gdal)
- ...

We should keep the images as small as possible by reducing any additional overhead.

**Comment by vsimko** [comment]
I currently replaced all gdal operations with geotrellis in my code.
Therefore, we can hibernate this issue for now.
